version: '3.8'

services:
  nginx-static:
    image: nginx:alpine
    container_name: et-static
    ports:
      - '${STATIC_PORT}:80'
    volumes:
      - ./static-server/static:/srv
      - ./static-server/nginx.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:alpine
    container_name: et-db
    environment:
      POSTGRES_DBNAME: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'

#  dashboard:
#    image: qobiljon/dashboard:1.2
#    container_name: et-dashboard
#    ports:
#      - '${APP_PORT}:8000'
